config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  resources :runs

  devise_for :users
  root "runs#index"
  get "about" => "pages#about"
  get "myruns" => "runs#myruns"
  get "summ" => "runs#summ"
  get "/:id" => "profiles#show"

end

app/models/run.rb
class Run < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates :distance, presence: true
	validates :rundate, presence: true
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :runs
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100" }#, :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name, presence: true
  validates :avatar, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :avatar, :password, :email) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :avatar, :password, :current_password) }
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
	@user = User.find_by_id(params[:id])
	if @user
		@runs = @user.runs.all.order("rundate DESC")
	render action: :show
	else
	render file: "public/404", status: 404, formats: [:html]
	end
end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy, :myruns]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @runs = Run.all.order("rundate DESC").paginate(:page => params[:page], :per_page => 50)
  end

  def show
  end

  def summ
    @users = User.all.order("name")
    @runs = Run.all
  end

  def myruns
    @runs = current_user.runs.order("rundate DESC").paginate(:page => params[:page], :per_page => 50)
  end

  def new
    @run = current_user.runs.build
  end

  def edit
  end

  def create
    @run = current_user.runs.build(run_params)
      if @run.save
        redirect_to @run, notice: 'Run was successfully uploaded.' 
      else
         render :new 
      end
  end

  def update
      if @run.update(run_params)
        redirect_to @run, notice: 'Run was successfully updated.'
      else
        render :edit 
      end
  end

  def destroy
    @run.destroy
    redirect_to runs_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find_by(id: params[:id])
    end

  def correct_user
    @run = current_user.runs.find_by(id: params[:id])
    redirect_to runs_path, notice: "Not authorized to edit this run" if @run.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:distance, :rundate, :image, :pace, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
     <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "100 Mile Run Club", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <% if user_signed_in? %>
        <li><%= link_to "Monthly Totals", summ_path %></li>
        <li><%= link_to "My Runs", myruns_path %></li>
          <li><%= link_to new_run_path do %>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Run 
            <%end%></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hundredmiles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Hundred Mile (+/-) Run Club</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About the Club</h1>
<%= image_tag("tess.jpg") %></br></br>
<p>This club was created in Tess' attempt to increase her monthly mileage total to 100 miles! To movitvate herself Tess is making her goal public, logging her miles and pace and even uploading pictures of her scenic runs. Since she's competitive by nature she's inviting fellow runners to do the same. Think she can do it?! Think you can do it? Faster? Better? More scenic? Lace up your shoes, join her on her quest and try to beat her to the finish line...</p>
<h2>What To Do:</h2>
<p>Pretty simple. Run 100 miles (+/-) per month.</p>
<h2>How To:</h2>
<p>Sign up for an account and upload an awesome profile picture to be displayed for your logged runs.</p>
<p>Track and upload your run details to this site. Enter the distance, pace and date of run. Want to show off that scenic run through the trees or brag about your breezy beach run? Upload a pic along with your run details and show us where you're hitting the pavement.</p>
<p>Be honest, have fun and starting running!</p>

app/views/profiles/show.html.erb
    <h1><strong><%= @user.name %>'s Runs</strong></h1>
<div id="runs" class="transitions-enabled">
    <% if @runs %>
	<% @runs.each do |run| %>
      <div class="box panel-default">
        <% if run.rundate >= Time.now.beginning_of_month - 1.month %>
        <% if run.image? %>
        <%= link_to image_tag(run.image.url(:medium)), run %>
        <% else %>
        <%= link_to image_tag(run.user.avatar.url(:medium)), run %>
        <% end %></br>  
        <% end %>      
        <div class="panel-body">
        <strong><%= run.user.name if run.user %></strong></br>
        <strong>Distance:</strong> <%= run.distance %><br/>
        <strong>Pace:</strong> <%= run.pace %><br/>
        <strong>Date:</strong> <%= run.rundate.strftime("%m/%d/%Y") %><br/>
        <% if current_user && run.user == current_user %>
        <div class="actions">
          <%= link_to edit_run_path(run) do %>
          <span class="glyphicon glyphicon-edit"></span>Edit
          <% end %>
          <%= link_to run, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>Delete
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/runs/_form.html.erb
<%= form_for @run, :html => { :multipart => true } do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %><br/>
    <% if @run.image.exists? %>
    <%= image_tag @run.image.url(:medium) %><br/><br/>
    <% end %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
   <div class="form-group">
    <%= f.label :pace %><br>
    <%= f.text_field :pace %>
  </div>
  <div class="form-group">
    <%= f.label :rundate %><br>
    <%= f.date_select :rundate %>
  </div>
  <div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to runs_path do %>
	<span class="glyphicon glyphicon-chevron-left"></span>Back
<% end %>

app/views/runs/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="runs" class="transitions-enabled">
    <% @runs.each do |run| %>
      <div class="box panel-default">
        <% if run.rundate >= Time.now.beginning_of_month - 1.month %>
        <% if run.image? %>
        <%= link_to image_tag(run.image.url(:medium)), "/" + run.user_id.to_s %>
        <% elsif run.user.avatar? %>
        <%= link_to image_tag(run.user.avatar.url(:medium)), "/" + run.user_id.to_s %>
        <% else %>
        <%= image_tag("runner.jpg") %>
        <% end %></br>
        <% end %>        
        <div class="panel-body">
        <strong><%= run.user.name if run.user %></strong></br>
        <strong>Distance:</strong> <%= run.distance %><br/>
        <strong>Pace:</strong> <%= run.pace %><br/>
        <strong>Date:</strong> <%= run.rundate.strftime("%m/%d/%Y") %><br/>
        <% if run.description? %>
        <strong>Description:</strong> <%= run.description %><br/>
        <% end %>
        <% if current_user && run.user == current_user %>
        <div class="actions">
          <%= link_to edit_run_path(run) do %>
          <span class="glyphicon glyphicon-edit"></span>Edit
          <% end %>
          <%= link_to run, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>Delete
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @runs, renderer: BootstrapPagination::Rails %>
</div>

app/views/runs/myruns.html.erb
<h1>My Runs</h1>
<div id="runs" class="transitions-enabled">
    <% @runs.each do |run| %>
    <% if current_user && run.user == current_user %>
      <div class="box panel-default">
       <% if run.rundate >= Time.now.beginning_of_month - 1.month %>
       <% if run.image? %>
        <%= link_to image_tag(run.image.url(:medium)), "/" + run.user_id.to_s %>
        <% elsif run.user.avatar? %>
        <%= link_to image_tag(run.user.avatar.url(:medium)), "/" + run.user_id.to_s %>
        <% else %>
        <%= image_tag("runner.jpg") %>
        <% end %></br>   
        <% end %>     
        <div class="panel-body">
        <strong><%= run.user.name if run.user %></strong></br>
        <strong>Distance:</strong> <%= run.distance %><br/>
        <strong>Pace:</strong> <%= run.pace %><br/>
        <strong>Date:</strong> <%= run.rundate.strftime("%m/%d/%Y") %><br/>
        <% if run.description? %>
        <strong>Description:</strong> <%= run.description %><br/>
        <% end %>
        <div class="actions">
          <%= link_to edit_run_path(run) do %>
          <span class="glyphicon glyphicon-edit"></span>Edit
          <% end %>
          <%= link_to run, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>Delete
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @runs, renderer: BootstrapPagination::Rails %>
</div>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<%= link_to runs_path do %>
	<span class="glyphicon glyphicon-chevron-left"></span>Back
<% end %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel-heading center">
		<% if @run.image? %>
        <%= link_to image_tag(@run.image.url(:medium)), "/" + @run.user_id.to_s %>
        <% elsif @run.user.avatar? %>
        <%= link_to image_tag(@run.user.avatar.url(:medium)), "/" + @run.user_id.to_s %>
        <% else %>
        <%= image_tag("runner.jpg") %>
        <% end %></br>
		</div>
			<div class="panel-body">
				<p><strong><%= @run.user.name if @run.user %></strong></p>
				<p><strong>Distance: </strong><%= @run.distance %></p>
				<p><strong>Pace: </strong><%= @run.pace %></p>
				<p><strong>Date: </strong><%= @run.rundate.strftime("%m/%d/%Y") %></p>	
				<% if @run.description? %>		
				<p><strong>Description: </strong><%= @run.description %></p>
				<% end %>
				<% if current_user && @run.user == current_user %>
					<%= link_to edit_run_path(@run) do %> 
						<span class="glyphicon glyphicon-edit"></span>Edit
					<% end %>
					<%= link_to @run, method: :delete, data: { confirm: 'Are you sure?' } do %>
         			 <span class="glyphicon glyphicon-trash"></span>Delete
          			<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/runs/summ.html.erb
<h1><center>Total Miles per Month</h1></center>
<div id="runs" class="transitions-enabled" >
	<% months = @runs.select("distinct DATE_TRUNC('month', rundate) AS month").order("DATE_TRUNC('month', rundate) desc")
	   months.each do |m|%>
	    <div class="box panel-default">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<%= image_tag("calendar.jpg") %></br></br>
					<h3 class="panel-title">
	   				<center><strong><font size=4><%= m.month.strftime("%B %Y") %></font></strong></center></h3>
	   			</div>    
				<ul class="list-group">
			      <% @users.each do |u|%>       
					 <% miles = @runs.select("DATE_TRUNC('month', rundate) AS month, user_id, COALESCE(sum(distance),0) as miles").where("DATE_TRUNC('month', rundate) = (?) and user_id = (?)", m.month, u.id).group("DATE_TRUNC('month', rundate), user_id")
					 miles.each do |x|%>
					 <% if !x.miles.nil? %>
					 <li class="list-group-item">
					 	<strong><%= u.name %>: </strong>
						 <%= x.miles %> miles</br>
						</li>
						<% end %>
					 <% end %>		 
				  <% end %>
				</ul>
			</div>
	   </div>
	<% end %>
</div>